### PR TITLE
Fraunhofer mapping list merge

### PR DESCRIPTION
**Pull request by kmajeshkrishnan**
RML list part of GUI and completely dockerized application with reverse proxy. Ready to merge if there are no problems of concern.

### CODE REVIEW

**Comment by TBoonX** [comment]
I was able to build and start the three services.
What not works is saving a mapping:

```
madamseditor.js?3864:241          POST http://localhost/python-backend/addrmlfile 422 (UNPROCESSABLE ENTITY)
handleClickSaveRmlBtn @ madamseditor.js?3864:241
eval @ madamseditor.js?3864:136
madamseditor.js?3864:394 error ['Upload failed: RML fle not accepted!']
```

The python-backend does not log to stdout thus I am unable to detect what the reason is.
@kmajeshkrishnan Do you have an idea?

**Comment by kmajeshkrishnan** [comment]
> I was able to build and start the three services. What not works is saving a mapping:
> 
> ```
> madamseditor.js?3864:241          POST http://localhost/python-backend/addrmlfile 422 (UNPROCESSABLE ENTITY)
> handleClickSaveRmlBtn @ madamseditor.js?3864:241
> eval @ madamseditor.js?3864:136
> madamseditor.js?3864:394 error ['Upload failed: RML fle not accepted!']
> ```
> 
> The python-backend does not log to stdout thus I am unable to detect what the reason is. @kmajeshkrishnan Do you have an idea?

I think virtuoso user doesn't have SPARQL permissions. Can you try creating a new user with all SPARQL operations enabled? I think by default it is not enabled for users, and re-run docker-compose.

**Comment by TBoonX** [comment]
I did execute
```
GRANT EXECUTE ON DB.DBA.SPARQL_INSERT_DICT_CONTENT TO "SPARQL";
GRANT EXECUTE ON DB.DBA.SPARQL_DELETE_DICT_CONTENT TO "SPARQL";
```
in Virtuoso and I am able to run insert commands on the /sparql path but I still get the error in the RML Editor. Is it possible to enable error logging in the python container to help me to identify the problem?

**Comment by kmajeshkrishnan** [comment]
Logs are visible now. I tested again by building from scratch. It works for me. Let me know how it goes.

**Comment by TBoonX** [comment]
OK my issue is that the browser tries to reach http://localhost/python-backend/addrmlfile but it is not reachable. Perhaps a nginx issue with my local machine.
Regarding our deployment in STREAM, the nginx from your branch will not be used because we have another nginx reverse proxy.
If you say that it works I will merge it.

**Pull request merged**
